### ISSUE TITLE
Error "Attempting to redefine object..."

### ISSUE THREAD

**Issue by ipuzek** [tskf/MapOfflineGPS#1]
Hi,

I am trying to build the data field on Windows for Edge 130 device. I followed all the instructions regarding the maps creation, but when trying to build I get the following errors:

ERROR: edge130: C:\"SOMEDIRS"\MapOfflineGPS\map.mc:5: Attempting to redefine object Map
ERROR: edge130: C:\"SOMEDIRS"\MapOfflineGPS\map.mc:8: Attempting to redefine object DataField

Any ideas?

Thanks, Ivan

**Comment by tskf** [comment]
I checked again and the code from repository is compiling for `-d edge130` without problems.

The error with redefined object occurs when there is a copy of source file in a project directory, including sub-directories. By default, the compiler reads every source file there, even with changed name. This usually happens after making a copy for editing, so be sure to separate that copy to other directory.

In a project, there must be no duplicates of objects in any `.mc` files. Except, it's possible, to change extension to `source_mc` or `source.copy`, with another extension a file won't be read.
